// ⚠️  PRODUCTION: VITE_API_BASE_URL environment variable MUST be set.
//    The localhost fallback is only safe for local development.
//    Set it in Vercel → Settings → Environment Variables.
const API_CONFIG = {
  BASE_URL: import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000',
  TIMEOUT: 30000,
};

export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    SIGNUP: '/auth/signup',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh',
  },
  USERS: {
    BASE: '/users',
    GET_ALL: '/users',
    CREATE: '/users/create',
    CREATE_STAFF: '/users/create-staff',
    DELETE: (id) => `/users/${id}`,
    UPDATE: (id) => `/users/${id}`,
    UPDATE_REFRESH_TOKEN: (id) => `/users/update-refresh-token/${id}`,
    GET_ALL_STAFF: (orgId) => `/users/find-all-staff-by-organization/${orgId}`,
  },
  ORGANIZATIONS: {
    BASE: '/organizations',
    GET_ALL: '/organizations',
    CREATE: '/organizations',
    UPDATE: (id) => `/organizations/${id}`,
    DELETE: (id) => `/organizations/${id}`,
    GET_SUBSCRIPTION: (id) => `/organizations/${id}/subscription`,
    UPDATE_SUBSCRIPTION: (id) => `/organizations/${id}/subscription`,
  },
  LETTER_SETTINGS: {
    GET: '/organizations/letter-settings',
    UPDATE: '/organizations/letter-settings',
    UPLOAD: '/organizations/letter-settings/upload',
  },
  AUTHORIZATION_LETTERS: {
    GET_ALL: '/authorization-letters',
    ELIGIBLE_AUCTIONS: '/authorization-letters/eligible-auctions',
    AUCTION_ELIGIBILITY: (auctionId) =>
      `/authorization-letters/auction/${auctionId}/eligibility`,
    CREATE: '/authorization-letters',
    GET_BY_ID: (id) => `/authorization-letters/${id}`,
    UPDATE: (id) => `/authorization-letters/${id}`,
    DELETE: (id) => `/authorization-letters/${id}`,
    PREVIEW: (id) => `/authorization-letters/${id}/preview`,
    PDF: (id) => `/authorization-letters/${id}/pdf`,
  },
  INVOICES: {
    BASE: '/invoice',
    GET_ALL: '/invoice',
    GET_BY_ID: (id) => `/invoice/${id}`,
    CREATE: '/invoice',
    UPDATE: (id) => `/invoice/${id}`,
    DELETE: (id) => `/invoice/${id}`,
    VEHICLE: {
      GET_ALL: '/invoice/vechile',
      CREATE: '/invoice/vechile',
      CREATE_BATCH: '/invoice/vechile/batch',
      GET_BY_ID: '/invoice/vechile',
      UPDATE: (id) => `/invoice/vechile/${id}`,
      DELETE: (id) => `/invoice/vechile/${id}`,
    },
    DOCUMENTS: {
      UPLOAD: '/invoice/purchase-documents',
      GET: '/invoice/purchase-documents',
    },
  },
  LEADS: {
    BASE: '/leads',
    GET_ALL: '/leads',
    GET_BY_ID: (id) => `/leads/${id}`,
    CREATE: '/leads',
    UPDATE: (id) => `/leads/${id}`,
    DELETE: (id) => `/leads/${id}`,
    ASSIGN: (id) => `/leads/${id}/assign`,
    UPDATE_STATUS: (id) => `/leads/${id}/status`,
    UPLOAD_DOCUMENTS: (id) => `/leads/${id}/documents`,
    GET_DOCUMENTS: (id) => `/leads/${id}/documents`,
    LOOKUP: '/leads/lookup',
    LOOKUP_BY_ID: (id) => `/leads/lookup/${id}`,
  },
  AUCTIONS: {
    BASE: '/auctions',
    GET_ALL: '/auctions',
    GET_BY_ID: (id) => `/auctions/${id}`,
    CREATE: '/auctions',
    UPDATE: (id) => `/auctions/${id}`,
    DELETE: (id) => `/auctions/${id}`,
    LOOKUP: '/auctions/lookup',
    LOOKUP_BY_ID: (id) => `/auctions/lookup/${id}`,
    CLOSE_DEAL: (id) => `/auctions/${id}/close-deal`,
    UPDATE_STATUS: (id) => `/auctions/${id}/status`,
    CANCEL: (id) => `/auctions/${id}/cancel`,
    LOTS: (id) => `/auctions/${id}/lots`,
    UPDATE_LOT: (id) => `/auctions/lots/${id}`,
    DELETE_LOT: (id) => `/auctions/lots/${id}`,
    LOT_VEHICLES: (lotId) => `/auctions/lots/${lotId}/vehicles`,
    LOT_VEHICLES_BATCH: (lotId) => `/auctions/lots/${lotId}/vehicles/batch`,
    UPDATE_VEHICLE: (id) => `/auctions/vehicles/${id}`,
    DELETE_VEHICLE: (id) => `/auctions/vehicles/${id}`,
    VEHICLE_IMAGES: (id) => `/auctions/vehicles/${id}/images`,
    LIFECYCLE: (id) => `/auctions/${id}/lifecycle`,
    LOT_OUTCOME: (id) => `/auctions/${id}/lifecycle/outcome`,
    LOT_PAYMENT: (lotId) => `/auctions/lots/${lotId}/payments`,
    LOT_ACCEPTANCE: (lotId) => `/auctions/lots/${lotId}/acceptance-letter`,
    LOT_DELIVERY: (lotId) => `/auctions/lots/${lotId}/delivery`,
    LOT_GATE_PASS: (lotId) => `/auctions/lots/${lotId}/gate-pass`,
    LOT_RCM: (lotId) => `/auctions/lots/${lotId}/rcm`,
  },
  INVENTORY: {
    BASE: '/inventory',
    GET_ALL: '/inventory',
    GET_BY_ID: (id) => `/inventory/${id}`,
    CREATE: '/inventory',
    UPDATE: (id) => `/inventory/${id}`,
    DELETE: (id) => `/inventory/${id}`,
  },
  PART_CATALOG: {
    MAKES: '/part-catalog/makes',
    MODELS: (makeId) => `/part-catalog/makes/${makeId}/models`,
    VARIANTS: (modelId) => `/part-catalog/models/${modelId}/variants`,
    VARIANT_PARTS: (variantId) => `/part-catalog/variants/${variantId}/parts`,
    CHECKLIST_VEHICLE: (vechileId) => `/part-catalog/checklist/vehicle/${vechileId}`,
    CHECKLIST_MMV: '/part-catalog/checklist/mmv',
    ADD_VARIANT_PART: (variantId) => `/part-catalog/variants/${variantId}/parts`,
    CATEGORIES: '/part-catalog/categories',
  },
  YARD: {
    VEHICLES: '/yard/vehicles',
    VEHICLE_BY_ID: (id) => `/yard/vehicles/${id}`,
    BY_VEHICLE_INVOICE: (vehicleInvoiceId) =>
      `/yard/vehicles/by-vehicle-invoice/${vehicleInvoiceId}`,
    MOVEMENTS: (id) => `/yard/vehicles/${id}/movements`,
    UPDATE_STATUS: (id) => `/yard/vehicles/${id}/status`,
    START_DISMANTLING: (vehicleInvoiceId) =>
      `/yard/vehicles/${vehicleInvoiceId}/start-dismantling`,
    DASHBOARD: '/yard/dashboard/summary',
    ZONES: '/yard/zones',
    CREATE_ZONE: '/yard/zones',
    BACKFILL: '/yard/backfill',
  },
  AUDIT_LOGS: {
    GET_ALL: '/audit-logs',
    GET_STAFF: '/audit-logs/staff',
    GET_BY_ID: (id) => `/audit-logs/${id}`,
  },
  VEHICLE_COMPLIANCE: {
    COD: {
      CREATE: '/vehicle-compliance/vechile-cod',
      GET_ALL: '/vehicle-compliance/vechile-cod',
      GET_BY_VEHICLE: (vehicleId) => `/vehicle-compliance/vechile-cod/vehicle/${vehicleId}`,
      UPDATE_RTO: (id) => `/vehicle-compliance/vechile-cod/${id}/rto`,
    },
  },
  SALES_DISPATCH: {
    BUYERS: {
      BASE: '/sales-dispatch/buyers',
      GET_ALL: '/sales-dispatch/buyers',
      GET_BY_ID: (id) => `/sales-dispatch/buyers/${id}`,
      CREATE: '/sales-dispatch/buyers',
      UPDATE: (id) => `/sales-dispatch/buyers/${id}`,
      DELETE: (id) => `/sales-dispatch/buyers/${id}`,
    },
    INVOICES: {
      BASE: '/sales-dispatch/invoices',
      GET_ALL: '/sales-dispatch/invoices',
      GET_BY_ID: (id) => `/sales-dispatch/invoices/${id}`,
      CREATE: '/sales-dispatch/invoices',
      UPDATE: (id) => `/sales-dispatch/invoices/${id}`,
      CONFIRM: (id) => `/sales-dispatch/invoices/${id}/confirm`,
      CANCEL: (id) => `/sales-dispatch/invoices/${id}/cancel`,
    },
  },
  TAX_COMPLIANCE: {
    CONFIG: '/tax-compliance/config',
    EWAY_BILLS: '/tax-compliance/eway-bills',
    EWAY_BILL_BY_INVOICE: (salesInvoiceId) => `/tax-compliance/eway-bills/invoice/${salesInvoiceId}`,
    GST_AUDIT_LOG: '/tax-compliance/gst-audit-log',
    GST_SUMMARY: '/reports/gst-summary',
  },
  DAMAGE_ADJUSTMENTS: {
    BASE: '/damage-adjustments',
    GET_ALL: '/damage-adjustments',
    CREATE: '/damage-adjustments',
  },
  ACCOUNTING: {
    CHART_OF_ACCOUNTS: '/accounting/chart-of-accounts',
    LEDGER_ENTRIES: '/accounting/ledger-entries',
    PNL: '/accounting/pnl',
    INVOICE_PAYMENTS: '/accounting/invoice-payments',
  },
  DASHBOARD: {
    OVERVIEW: '/dashboard/overview',
  },
};

export default API_CONFIG;
